name: deploy-manifests

on:
  workflow_dispatch: # Put here!! to allow manual triggering
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: echo ">>> its 6/21 120pm <<<"
      - run: doctl kubernetes cluster kubeconfig save ticketing-cluster
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
